version: 2
registries:
  takumi-guard-pypi:
    type: python-index
    url: https://pypi.flatt.tech/simple/

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/packages/local"
    registries:
      - takumi-guard-pypi
    schedule:
      interval: "weekly"
    groups:
      local-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/packages/gcp-functions/check-new-video"
    registries:
      - takumi-guard-pypi
    schedule:
      interval: "weekly"
    groups:
      check-new-video-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/packages/obs-title-updater"
    registries:
      - takumi-guard-pypi
    schedule:
      interval: "weekly"
    groups:
      obs-title-updater-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/packages/report-generator"
    registries:
      - takumi-guard-pypi
    schedule:
      interval: "weekly"
    groups:
      report-generator-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/packages/web"
    schedule:
      interval: "weekly"
    groups:
      web-dependencies:
        patterns:
          - "*"
