name: CI - packages/gcp-functions/check-new-video

on:
  push:
    paths:
      - "packages/gcp-functions/check-new-video/**"
  pull_request:
    paths:
      - "packages/gcp-functions/check-new-video/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/gcp-functions/check-new-video

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Test
        run: uv run pytest
